backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'public/uploads' # Where media files will be stored
public_folder: '/uploads' # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/blogs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title Tag', name: 'titleTag', widget: 'string' }
      - { label: 'Meta Description', name: 'metaDescription', widget: 'string' }
      - { label: 'OG Title', name: 'ogTitle', widget: 'string' }
      - { label: 'OG Description', name: 'ogDescription', widget: 'string' }
      - { label: 'OG Image', name: 'ogImage', widget: 'image' }
      - { label: 'Twitter Title', name: 'twitterTitle', widget: 'string' }
      - {
          label: 'Twitter Description',
          name: 'twitterDescription',
          widget: 'string',
        }
      - { label: 'Twitter Image', name: 'twitterImage', widget: 'image' }
      - {
          label: 'Event Name For Tracking',
          name: 'eventNameForTracking',
          widget: 'string',
        }
      - {
          label: 'Event ID For Tracking',
          name: 'eventIdForTracking',
          widget: 'string',
        }
      - { label: 'Blog Title', name: 'blogTitle', widget: 'string' }
      - { label: 'Author', name: 'blogAuthor', widget: 'string' }
      - {
          label: 'Author Description',
          name: 'authorDescription',
          widget: 'string',
        }
      - { label: 'Author Image', name: 'authorImage', widget: 'image' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'string' }
      - { label: 'Time To Read', name: 'timeToRead', widget: 'string' }
      - {
          label: 'Blog Image',
          name: 'blogImage',
          widget: 'image',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
